### ISSUE TITLE
parsing of floating point numbers in ffprobe output

### ISSUE THREAD

**Issue by m-bene** [hudl/HudlFfmpeg#15]
when using the library on a system with different number format (semicolon as decimal separator and full stop as group separator), parsing of duration attribute fails.

SerializeAsFFprobeDouble could use 
````
double.TryParse(ffprobeObject.Value.ToString(), NumberStyles.Number, CultureInfo.InvariantCulture, out value)
````
instead of 
````
double.TryParse(ffprobeObject.Value.ToString(), out value)
````

**Comment by Casey-Bateman** [comment]
Thankyou for your submission, we should have this in the next release.
