### ISSUE TITLE
decode h264 stream

### ISSUE THREAD

**Issue by abhinav4ever** [hudl/HudlFfmpeg#16]
Is it possible to decode stream of bytes encoded in H264_ES with this wrapper?

**Comment by Casey-Bateman** [comment]
Though this is not currently supported within this wrapper, it is feasible using the piping protocol within ffmpeg. 

We would need to create a new resource type of Stream, then pipe the input stream to the ffmpeg executable.

Is that what you are requesting?

**Comment by abhinav4ever** [comment]
yea something that would take stream of bytes and output yuv frames in a loop.However, I ended up using MS Media Foundation h264 decoder mainly because of no licencing issue.
