### ISSUE TITLE
How to convert both audio and video streams

### ISSUE THREAD

**Issue by rajinders** [hudl/HudlFfmpeg#18]
Hi:

I have a video in H.263 format. Audio stream including in the container is in AMR format.
I need to convert these in H.264 and AAC format.

If I use ffmpeg command line I can do this 
ffmpeg -i c:\videos\input\inh263.mp4 -vcodec h264 -f mp4 c:\videos\output\outh264.mp4

The resulting video is H264 and audio is AAC.

Can you provide an example for how to do the same conversion using your API?

Thanks

**Comment by Casey-Bateman** [comment]
Yes, very sorry for such a late response.

1. first you would need to create a ```CommandFactory```
2. second you would create your output settings collection.
2. you would use Hudl.FFmpeg.Sugar syntax to create the command
4. you would render the command factory

```
var factory = CommandFactory.Create()

var settingsOut = SettingsCollection.ForOutput(new OutputFormat("mp4"), new VideoCodec("libx264"));

factory.AsOutput()
       .AddInput("C:\videos\input\inh263.mp4")
       .To<Mp4>("C:\videos\output\outh264.mp4", settingsOut)

factory.Render();
```
