### ISSUE TITLE
 encoding video Process

### ISSUE THREAD

**Issue by 276544061** [hudl/HudlFfmpeg#21]
I want to get the process to sync with server.How to do? Thanks

**Comment by Casey-Bateman** [comment]
Which process are you speaking of? The ffmpeg process? Im not sure I get what you are meaning by sync with server?

**Comment by 276544061** [comment]
just like 0% .. 20%.. 90%.. and so on

**Comment by Casey-Bateman** [comment]
The process is not currently exposed in the command editor, It would take some enhancements to get something like this in the framework.

**Comment by 276544061** [comment]
thanks
