### ISSUE TITLE
Which audio encoders/decoders are included in this library

### ISSUE THREAD

**Issue by jd-alexander** [hudl/HudlFfmpeg#25]
Firstly I would like to save great library. I have been searching for a proper ffmpeg library for weeks. I'm a newb to this all so I was wondering which codecs are supported by default ffmpeg. I know the library sits on top of the pre existing ffmpeg instance however I'm still not clear on how to determine what's available and how to install additional codecs. I am planning to work with mp4 and possibly mp3 audio files. I am interested in trimming them, merging them and also increasing their respective volumes. Thanks for your help.

**Comment by Casey-Bateman** [comment]
Hey, thank you for your kind words. If you download the static builds from ffmpeg.org you can run ```ffmpeg -codecs``` which will give you a list of all the codecs that are packaged by default. 

If you are wanting to work with mp4 (h264) video and mp3 audio files then the codecs necessary are already packaged by default in the static builds. 

If you are wanting to add additional codecs, you will need to compile from source and enable the codecs that you want. For the purposes explained in your post, the static builds will suit your needs.

Thanks!

**Comment by jd-alexander** [comment]
Alright thanks alot!
