### ISSUE TITLE
CrossfadeConcatenate referenced in RenderTests

### ISSUE THREAD

**Issue by killswtch** [hudl/HudlFfmpeg#26]
The filter chain template CrossfadeConcatenate is referenced in Hudl.FFmpeg.Tests.Render.RenderTests, but that class no longer exists. It appears that it has been replaced with the Dissolve class, in which case the reference needs updating. Cannot build in DEBUG configuration until resolved.

**Comment by Casey-Bateman** [comment]
this is resolved now in 3.2.0
