### ISSUE TITLE
Space missing between settings

### ISSUE THREAD

**Issue by killswtch** [hudl/HudlFfmpeg#29]
Space is not being added between settings, leading to the end of one setting being 'stuck' to the start of the next. I've made a potential fix by chaning line 184 of FFmpegCommandBuilder.cs to `output.Settings.SettingsList.ForEach(setting => BuilderBase.AppendFormat(" {0}", SettingSerializer.Serialize(setting)));` but I'm not certain that this is the correct place to introduce the space character. I'm also having difficulties with Git at the moment, so haven't committed.

**Comment by Casey-Bateman** [comment]
this should also be fixed in 3.2.0
