### ISSUE TITLE
Links to full API documentation take you to an empty page

### ISSUE THREAD

**Issue by GFoley83** [hudl/HudlFfmpeg#43]
Can seem to find a working link to the full documentation. All links lead to this page:
https://github.com/hudl/HudlFfmpeg/wiki/doc/api.md
or back to the wiki.

**Comment by Casey-Bateman** [comment]
@GFoley83 sorry for the late response, The full API documentation was removed, It would seem as though i missed some links. 

I have been exploring better ways to provide a full breakdown on features, github wiki has not been the best way to maintain that. 

On that note, i would be happy to answer any questions that you have.

**Comment by simonbuehler** [comment]
maybe a Sample App with all kinds of examples would be great, giving a hint on the best practice usage of the sugar etc. What i'm also  misisng is the difference between select() and take()

**Comment by GFoley83** [comment]
:+1:

**Comment by Casey-Bateman** [comment]
Closing and opening new issue for sample application. https://github.com/hudl/HudlFfmpeg/issues/53
