### ISSUE TITLE
Add sample application with best practices

### ISSUE THREAD

**Issue by Casey-Bateman** [hudl/HudlFfmpeg#53]
Request for additional documentation, and a sample application with best practices on how to use the framework.

**Comment by jbraun27** [comment]
Thanks @Casey-Bateman, nice to see that this project is getting some TLC

**Comment by Casey-Bateman** [comment]
@jbraun27 If you have any requests for documentation, or samples let me know, I would be happy to add them in any time.

**Comment by Casey-Bateman** [comment]
Released under the Samples directory.
