### ISSUE TITLE
Required functionality - cropdetect filter

### ISSUE THREAD

**Issue by iprida** [hudl/HudlFfmpeg#56]
I want to implement [cropdetect](http://ffmpeg.org/ffmpeg-filters.html#cropdetect) filter. But I don't see any mecanism to process the ffmpeg process output messages. Any advice?

**Comment by Casey-Bateman** [comment]
@iprida I am working on cutting a new version of Hudl.FFmpeg today v3.4.0. In this version you will be able to attach an `OnSuccess` or `OnError` handler to each command that you send through. You will have full access to the `StandardOutput` stream from these so you will be able to process the results.

**Comment by Casey-Bateman** [comment]
Released, Check the Samples application for the `AttachOnSuccessOnErrorsEvents` sample to see how to work with ffmpeg output.

**Comment by iprida** [comment]
Thank you!
