### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by blainekasten** [hudl/HudlFfmpeg#57]
This project needs a maintained changelog. The current tag releases don't provide any context for outside devs to know how a new version will affect them.

**Comment by Casey-Bateman** [comment]
@blainekasten the current changelog is in the wiki, however i know it is more standard in OSS projects to have a changelog in the main dir. 

I will get it moved.

**Comment by blainekasten** [comment]
+1. It'd be good to have the changes tied to the tagged releases also instead of just saying: `Stable x.x.x`
